# Generated by Django 6.0.7 on 2026-07-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dim1', models.IntegerField(help_text='Smallest dimension')),
                ('dim2', models.IntegerField(help_text='Middle dimension')),
                ('dim3', models.IntegerField(help_text='Largest dimension')),
                ('max_weight', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['cost'],
            },
        ),
    ]
